# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255, null=True, blank=True)),
                ('kelas', models.CharField(max_length=100, null=True, blank=True)),
                ('nis', models.CharField(max_length=100, unique=True, null=True, blank=True)),
                ('is_active', models.BooleanField(null=True, blank=True)),
            ],
            options={
                'db_table': 'siswa',
            },
        ),

        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255, null=True, blank=True)),
                ('pengarang', models.CharField(max_length=255, null=True, blank=True)),
                ('ketagori', models.CharField(max_length=255, null=True, blank=True)),
                ('penerbit', models.CharField(max_length=255, null=True, blank=True)),
                ('tahun_terbit', models.IntegerField(null=True, blank=True)),
                ('rak', models.CharField(max_length=100, null=True, blank=True)),
                ('stok', models.IntegerField(null=True, blank=True)),
                ('deskripsi', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'buku',
            },
        ),

        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pinjam', models.DateField(null=True, blank=True)),
                ('jatuh_tempo', models.DateField(null=True, blank=True)),
                ('keperluan', models.TextField(null=True, blank=True)),
                ('status', models.CharField(max_length=100, null=True, blank=True)),
                (
                    'buku',
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        to='peminjam.buku',
                        db_column='buku_id',
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    'siswa',
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        to='peminjam.siswa',
                        db_column='siswa_id',
                        null=True,
                        blank=True,
                    ),
                ),
            ],
            options={
                'db_table': 'peminjaman',
            },
        ),
    ]